import { LifeGameProvider } from "@nolix2/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import type { ReactNode } from "react";
import A from "./A";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: any;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<LifeGameProvider>
					<A />
					{children}
				</LifeGameProvider>
			</body>
		</html>
	);
}
